# Generated by Django 4.1.5 on 2023-02-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namec', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(choices=[('Hu', 'Humanities'), ('So', 'Social Science'), ('Na', 'Natural Science'), ('Fo', 'Formal Science'), ('Ap', 'Applied Science')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('purpose', models.TextField(choices=[('En', 'Enquiry'), ('Or', 'Order'), ('Re', 'Return')])),
                ('materials', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='schoolapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='schoolapp.dep')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.dep'),
        ),
    ]
