# Generated by Django 4.1.5 on 2023-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='named',
            field=models.CharField(max_length=20),
        ),
    ]
