# Generated by Django 4.1.5 on 2023-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_dep_named'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='materials',
            field=models.TextField(blank=True, choices=[('Paper', 'Paper'), ('Pen', 'Pen'), ('Text', 'Text Book'), ('Note', 'Note Book')], null=True),
        ),
        migrations.AlterField(
            model_name='req',
            name='purpose',
            field=models.CharField(choices=[('En', 'Enquiry'), ('Or', 'Order'), ('Re', 'Return')], max_length=50),
        ),
    ]
