# Generated by Django 4.1.5 on 2023-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_req_materials_alter_req_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='req',
            name='purpose',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Order', 'Order'), ('Return', 'Return')], max_length=50),
        ),
    ]
