# Generated by Django 4.1.5 on 2023-02-23 18:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departmnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rdob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Order', 'Order'), ('Return', 'Return')], max_length=50)),
                ('materials', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rcourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp_2.course')),
                ('rdept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp_2.departmnt')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='deptid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp_2.departmnt'),
        ),
    ]
