# Generated by Django 4.1.5 on 2023-02-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmnt',
            new_name='Department',
        ),
    ]
