# Generated by Django 4.1.5 on 2023-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp_2', '0002_rename_departmnt_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='materials',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
